app/aliases/models.py
from sqlalchemy.orm import relationship

from app.accounts.models import User
from app.db import db


class Alias(db.Model):
    __tablename__ = 'aliases'

    id = db.Column(db.Integer, primary_key=True)
    ip_address = db.Column(db.String(32), nullable=False)
    alias = db.Column(db.String(64), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey(User.id, ondelete='CASCADE'), nullable=False)

    user = relationship('User', foreign_keys='Alias.user_id')

    def __repr__(self):
        return f'<Alias {self.id}>'

app/aliases/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators


class AddAliasForm(FlaskForm):
    ip_address = StringField(
        validators=[
            validators.DataRequired(),
            validators.Length(max=19),
            validators.Regexp(regex=r'^(\d{1,3}\.){3}\d{1,3}$', message='Invalid IP')
        ]
    )
    alias = StringField(
        validators=[
            validators.DataRequired(),
            validators.Length(max=64)
        ]
    )


class EditAliasForm(FlaskForm):
    alias = StringField(
        validators=[
            validators.DataRequired(),
            validators.Length(max=64)
        ]
    )

app/aliases/controllers.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, abort
from flask_login import login_required, current_user

from app.aliases.db_services import create_alias, get_aliases_by_user_id, destroy_alias_by_id, get_alias_by_id, update_alias
from app.aliases.decorators import alias_owner
from app.aliases.forms import AddAliasForm, EditAliasForm

aliases_bp = Blueprint('aliases', __name__, template_folder='templates')


@aliases_bp.route('/add_alias', methods=('GET', 'POST'))
@login_required
def add_alias():
    form = AddAliasForm(request.form)

    if request.method == 'POST' and form.validate():
        try:
            create_alias(form.ip_address.data, form.alias.data, current_user)
        except Exception as e:
            flash(str(e) or 'Unknown error', 'error')
            return redirect(url_for('aliases.add_alias'))
        else:
            return redirect(url_for('aliases.aliases'))

    return render_template('aliases/add_alias.html', username=current_user.username, form=form)


@aliases_bp.route('/edit_alias/<alias_id>', methods=('GET', 'POST'))
@login_required
@alias_owner
def edit_alias(alias_id):
    form = EditAliasForm(request.form)

    if request.method == 'POST' and form.validate():
        try:
            update_alias(alias_id, form.alias.data)
        except Exception as e:
            flash(str(e) or 'Unknown error', 'error')
            return redirect(url_for('aliases.edit_alias'))
        else:
            return redirect(url_for('aliases.aliases'))

    try:
        data = {
            'username': current_user.username,
            'alias': get_alias_by_id(alias_id),
            'form': form
        }
    except Exception as e:
        flash(str(e) or 'Unknown error', 'error')
        abort(404)
    else:
        return render_template('aliases/edit_alias.html', **data)


@aliases_bp.route('/aliases', methods=('GET',))
@login_required
def aliases():
    try:
        data = {
            'username': current_user.username,
            'aliases': get_aliases_by_user_id(current_user.id)
        }
    except Exception as e:
        flash(str(e) or 'Unknown error', 'error')
        abort(404)
    else:
        return render_template('aliases/aliases.html', **data)


@aliases_bp.route('/delete_alias/<alias_id>', methods=('GET',))
@login_required
@alias_owner
def delete_alias(alias_id):
    try:
        destroy_alias_by_id(alias_id)
    except Exception as e:
        flash(str(e) or 'Unknown error', 'error')
        abort(404)
    else:
        return redirect(url_for('aliases.aliases'))

app/aliases/templates/aliases/add_alias.html
{% extends "authorized/layout.html" %}

{% block authorized_content_title %}Add alias{% endblock %}

{% block authorized_content_inner %}
    <form method="post">
        {{ form.csrf_token }}
        <div class="block">
            {% if get_flashed_messages() %}
                <p class="has-text-danger has-text-centered">{{ get_flashed_messages()[0] }}</p>
            {% endif %}
            <div class="field">
                <label class="label has-text-white-bis has-text-weight-medium" for="ip_address">IP address <span class="has-text-danger">*</span></label>
                <div class="control has-icons-left">
                    <input required class="input {% if form.ip_address.errors %}is-danger{% endif %}" id="ip_address" name="ip_address" type="text" placeholder="e.g. 192.168.0.1" maxlength="15" value="{{ form.ip_address.data }}">
                    <span class="icon is-small is-left">
                        <i class="fas fa-map-marker-alt"></i>
                    </span>
                </div>
                {% if form.ip_address.errors %}
                    <p class="help is-danger">{{ form.ip_address.errors[0] }}</p>
                {% endif %}
            </div>
            <div class="field">
                <label class="label has-text-white-bis has-text-weight-medium" for="alias">Alias <span class="has-text-danger">*</span></label>
                <div class="control has-icons-left">
                    <input required class="input {% if form.alias.errors %}is-danger{% endif %}" id="alias" name="alias" type="text" placeholder="e.g. John" maxlength="64" value="{{ form.alias.data }}">
                    <span class="icon is-small is-left">
                        <i class="fas fa-user-tag"></i>
                    </span>
                </div>
                {% if form.alias.errors %}
                    <p class="help is-danger">{{ form.alias.errors[0] }}</p>
                {% endif %}
            </div>
        </div>
        <div class="block">
            <button class="button is-primary w-full">Add</button>
        </div>
    </form>
{% endblock %}

app/aliases/templates/aliases/aliases.html
{% extends "authorized/layout.html" %}

{% block authorized_content_title %}My aliases{% endblock %}

{% block authorized_content_inner %}
    <div class="block">
        <table class="table w-full is-border-none has-background-transparent">
            <thead>
                <tr>
                    <th class="has-text-white">Alias</th>
                    <th class="has-text-white">IP-address</th>
                    <th class="has-text-white"></th>
                </tr>
            </thead>
            <tbody>
                {% for alias in aliases %}
                    <tr>
                        <td class="has-text-grey-light">{{ alias.alias }}</td>
                        <td class="has-text-grey-light">{{ alias.ip_address }}</td>
                        <td class="has-text-grey-light is-flex is-justify-content-end">
                            <div class="buttons">
                                <a class="button is-light is-small mr-3" href="{{ url_for('aliases.edit_alias', alias_id=alias.id) }}">Edit</a>
                                <a class="button is-danger is-small" href="{{ url_for('aliases.delete_alias', alias_id=alias.id) }}">Delete</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="block">
        <a class="button is-primary py-3 px-5 is-flex is-justify-content-center is-align-items-center" href="{{ url_for('aliases.add_alias') }}">Add alias</a>
    </div>
{% endblock %}

app/aliases/templates/aliases/edit_alias.html
{% extends "authorized/layout.html" %}

{% block authorized_content_title %}Edit alias{% endblock %}

{% block authorized_content_inner %}
    <form method="post">
        {{ form.csrf_token }}
        <div class="block">
            {% if get_flashed_messages() %}
                <p class="has-text-danger has-text-centered">{{ get_flashed_messages()[0] }}</p>
            {% endif %}
            <div class="field">
                <label class="label has-text-white-bis has-text-weight-medium" for="ip_address">IP address</label>
                <div class="control has-icons-left">
                    <input disabled class="input" id="ip_address" name="ip_address" type="text" placeholder="e.g. 192.168.0.1" value="{{ alias.ip_address }}">
                    <span class="icon is-small is-left">
                        <i class="fas fa-map-marker-alt"></i>
                    </span>
                </div>
            </div>
            <div class="field">
                <label class="label has-text-white-bis has-text-weight-medium" for="alias">Alias</label>
                <div class="control has-icons-left">
                    <input required class="input" id="alias" name="alias" type="text" placeholder="e.g. John" value="{{ alias.alias }}">
                    <span class="icon is-small is-left">
                        <i class="fas fa-user-tag"></i>
                    </span>
                </div>
                {% if form.alias.errors %}
                    <p class="help is-danger">{{ form.alias.errors[0] }}</p>
                {% endif %}
            </div>
        </div>
        <div class="block">
            <button class="button is-primary w-full">Save</button>
        </div>
    </form>
{% endblock %}