app/links/models.py
import datetime

from sqlalchemy.orm import relationship

from app.accounts.models import User
from app.db import db


class Link(db.Model):
    __tablename__ = 'links'

    id = db.Column(db.Integer, primary_key=True)
    redirect_link = db.Column(db.String(256), nullable=False)
    target_link = db.Column(db.String(256), nullable=False)
    label = db.Column(db.String(64), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey(User.id, ondelete='CASCADE'), nullable=False)

    user = relationship('User', foreign_keys='Link.user_id')

    def __repr__(self):
        return f'<Link {self.id}>'


class Visit(db.Model):
    __tablename__ = 'visits'

    id = db.Column(db.Integer, primary_key=True)
    ip_address = db.Column(db.String(32), nullable=False)
    location = db.Column(db.String(256), nullable=False)
    time_visited = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    link_id = db.Column(db.Integer, db.ForeignKey(Link.id, ondelete='CASCADE'), nullable=False)

    link = relationship('Link', foreign_keys='Visit.link_id')

    def __repr__(self):
        return f'<Visit {self.id}>'

app/links/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators


class AddLinkForm(FlaskForm):
    target_link = StringField(
        validators=[
            validators.DataRequired(),
            validators.Length(max=256),
            validators.Regexp(regex=r'^https?:\/\/\S*$', message='Invalid link')
        ]
    )
    label = StringField(
        validators=[
            validators.Length(max=64)
        ]
    )

app/links/controllers.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, abort
from flask_login import login_required, current_user

from app.links.db_services import (
    create_link, get_links_by_user_id, get_link_by_id, create_visit,
    get_visits_by_link_id, destroy_link_by_id,
)
from app.links.decorators import link_owner
from app.links.forms import AddLinkForm
from app.links.services import get_visits_with_label, serialize_new_visits, get_ip_from_request

links_bp = Blueprint('links', __name__, template_folder='templates')


@links_bp.route('/add_link', methods=('GET', 'POST'))
@login_required
def add_link():
    form = AddLinkForm(request.form)

    if request.method == 'POST' and form.validate():
        try:
            create_link(form.target_link.data, form.label.data, current_user)
        except Exception as e:
            flash(str(e) or 'Unknown error', 'error')
            return redirect(url_for('links.add_link'))
        else:
            return redirect(url_for('links.links'))

    return render_template('links/add_link.html', username=current_user.username, form=form)


@links_bp.route('/link/<link_id>', methods=('GET', 'POST'))
@login_required
@link_owner
def link(link_id):
    try:
        if request.method == 'POST':
            return {'new_visits': serialize_new_visits(get_visits_with_label(get_visits_by_link_id(link_id)))}
        data = {
            'username': current_user.username,
            'link': get_link_by_id(link_id),
            'visits': get_visits_with_label(get_visits_by_link_id(link_id))
        }
    except Exception as e:
        flash(str(e) or 'Unknown error', 'error')
        abort(404)
    else:
        return render_template('links/link.html', **data)


@links_bp.route('/links', methods=('GET',))
@login_required
def links():
    try:
        data = {
            'username': current_user.username,
            'links': get_links_by_user_id(current_user.id)
        }
    except Exception as e:
        flash(str(e) or 'Unknown error', 'error')
        abort(404)
    else:
        return render_template('links/links.html', **data)


@links_bp.route('/add_visit/<link_id>', methods=('GET',))
def add_visit(link_id):
    try:
        link_by_id = get_link_by_id(link_id)
        create_visit(get_ip_from_request(request), link_by_id)
    except Exception as e:
        flash(str(e) or 'Unknown error', 'error')
        abort(404)
    else:
        return redirect(link_by_id.target_link)


@links_bp.route('/delete_link/<link_id>', methods=('GET',))
@login_required
@link_owner
def delete_link(link_id):
    try:
        destroy_link_by_id(link_id)
    except Exception as e:
        flash(str(e) or 'Unknown error', 'error')
        abort(404)
    else:
        return redirect(url_for('links.links'))

app/links/templates/links/add_link.html
{% extends "authorized/layout.html" %}

{% block authorized_content_title %}Add link{% endblock %}

{% block authorized_content_inner %}
    <form method="post">
        {{ form.csrf_token }}
        <div class="block">
            {% if get_flashed_messages() %}
                <p class="has-text-danger has-text-centered">{{ get_flashed_messages()[0] }}</p>
            {% endif %}
            <div class="field">
                <label class="label has-text-white-bis has-text-weight-medium" for="target_link">Target link <span class="has-text-danger">*</span></label>
                <div class="control has-icons-left">
                    <input required class="input {% if form.target_link.errors %}is-danger{% endif %}" id="target_link" name="target_link" type="text" placeholder="e.g. http://127.0.0.1:5000" maxlength="256" value="{{ form.target_link.data }}">
                    <span class="icon is-small is-left">
                        <i class="fas fa-link"></i>
                    </span>
                </div>
                {% if form.target_link.errors %}
                    <p class="help is-danger">{{ form.target_link.errors[0] }}</p>
                {% endif %}
            </div>
            <div class="field">
                <label class="label has-text-white-bis has-text-weight-medium" for="label">Label</label>
                <div class="control has-icons-left">
                    <input class="input {% if form.label.errors %}is-danger{% endif %}" id="label" name="label" type="text" placeholder="e.g. My Super Link" maxlength="64" value="{{ form.label.data }}">
                    <span class="icon is-small is-left">
                        <i class="fas fa-tag"></i>
                    </span>
                </div>
                {% if form.label.errors %}
                    <p class="help is-danger">{{ form.label.errors[0] }}</p>
                {% endif %}
            </div>
        </div>
        <div class="block">
            <button class="button is-primary w-full">Add</button>
        </div>
    </form>
{% endblock %}

app/links/templates/links/link.html
{% extends "authorized/layout.html" %}

{% block authorized_content_title %}
    <span>Link</span>
    <span class="has-text-grey-light has-text-weight-medium">
        {% if link.label %}
            &laquo;{{ link.label }}&raquo;
        {% else %}
            &laquo;{{ link.target_link }}&raquo;
        {% endif %}
    </span>
{% endblock %}

{% block authorized_content_inner %}
    <div class="block">
        <div class="field has-addons">
            <div class="control w-full">
                <label class="is-sr-only" for="redirect-link"></label>
                <input disabled class="input pl-5" id="redirect-link" name="redirect-link" type="text" value="{{ link.redirect_link }}">
            </div>
            <div class="control">
                <button class="button is-primary pr-5" id="copy-redirect-link-btn">Copy</button>
            </div>
        </div>
    </div>
    <div class="block">
        <table class="table w-full has-background-transparent">
            <thead>
                <tr>
                    <th class="has-text-white">IP-address/Label</th>
                    <th class="has-text-white">Location</th>
                    <th class="has-text-white">Time visited</th>
                </tr>
            </thead>
            <tbody id="visits">
                {% for visit in visits %}
                     <tr>
                        <td class="has-text-grey-light">{{ visit.label }}</td>
                        <td class="has-text-grey-light">{{ visit.location }}</td>
                        <td class="has-text-grey-light">{{ visit.time_visited|prettify_datetime }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        $(document).ready(function() {
            setInterval(() => {
                $.ajax({
                    type: 'POST',
                    url: window.location.href,
                    xhrFields: {
                       withCredentials: true
                    },
                    success: response => {
                        const newVisits = response['new_visits'];
                        const visitsTable = $('#visits');
                        newVisits.forEach(visit => {
                            const visitTR = $('<tr></tr>');
                            visitTR.append($('<td class="has-text-grey-light"></td>').text(visit['label']));
                            visitTR.append($('<td class="has-text-grey-light"></td>').text(visit['location']));
                            visitTR.append($('<td class="has-text-grey-light"></td>').text(visit['time_visited']));
                            visitsTable.prepend(visitTR);
                        });
                    }
                });
            }, 5000);
            $('#copy-redirect-link-btn')[0].addEventListener('click', e => {
                const redirectLinkInput = $('input#redirect-link');
                redirectLinkInput.prop('disabled', false);
                redirectLinkInput.focus();
                redirectLinkInput.select();
                document.execCommand('copy');
                redirectLinkInput.blur();
                if (window.getSelection) {window.getSelection().removeAllRanges();}
                else if (document.selection) {document.selection.empty();}
                redirectLinkInput.prop('disabled', true);
            });
        });
    </script>
{% endblock %}

app/links/templates/links/links.html
{% extends "authorized/layout.html" %}

{% block authorized_content_title %}My links{% endblock %}

{% block authorized_content_inner %}
    <div class="block">
        {% for link in links %}
            <div class="block py-3 px-5 is-flex is-justify-content-space-between is-align-items-center is-slightly-rounded has-background-black-ter">
                <div class="has-text-white-bis">
                    {% if link.label %}
                        {{ link.label }}
                    {% else %}
                        {{ link.target_link }}
                    {% endif %}
                </div>
                <div class="buttons">
                    <a class="button is-white is-inverted has-background-transparent is-small" href="{{ url_for('links.link', link_id=link.id) }}">View</a>
                    <a class="button is-danger is-outlined is-small" href="{{ url_for('links.delete_link', link_id=link.id) }}">Delete</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="block">
        <a class="button is-primary py-3 px-5 is-flex is-justify-content-center is-align-items-center" href="{{ url_for('links.add_link') }}">Add link</a>
    </div>
{% endblock %}